# Auto-generated by tierb_onboard.py -- weights-baked serving image (cold-start fix #2).
FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-runtime
ENV HF_HOME=/app/hf HF_HUB_ENABLE_HF_TRANSFER=1 PYTHONUNBUFFERED=1
WORKDIR /app
ARG HF_TOKEN=
ENV HF_TOKEN=${HF_TOKEN}
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt fastapi uvicorn python-multipart requests pillow hf_transfer timm kornia einops accelerate scipy sentencepiece opencv-python-headless
# bake the model weights into the image layer so cold start does NO download:
RUN python -c "import os; from huggingface_hub import snapshot_download; snapshot_download('ZhengPeng7/BiRefNet', token=os.environ.get('HF_TOKEN') or None)"
# weights are baked now -> force cache-only at RUNTIME (proves + guarantees zero cold-start download)
ENV HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1
COPY serve.py .
EXPOSE 8000
CMD ["python","-m","uvicorn","serve:app","--host","0.0.0.0","--port","8000"]
